<?php

namespace AppBundle\Repository;

/**
 * ChecklistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistItemRepository extends \Doctrine\ORM\EntityRepository
{
}
