<?php

namespace AppBundle\Repository;

/**
 * ChecklistMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
