<?php

namespace AppBundle\Repository;

/**
 * MailPreformatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailPreformatRepository extends \Doctrine\ORM\EntityRepository
{
}
