<?php

namespace AppBundle\Repository;

/**
 * Reminder
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderRepository extends \Doctrine\ORM\EntityRepository
{
}
