<?php

namespace AppBundle\Repository;

/**
 * ServerReminderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerReminderRepository extends \Doctrine\ORM\EntityRepository
{
}
