<?php

namespace AppBundle\Repository;

/**
 * SupportTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
