login:
    type: rest
    resource: AppBundle\Controller\RestLoginController


password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController


profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController


registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController

project:
    type: rest
    resource: AppBundle\Controller\ProjectController

checklist:
    type: rest
    resource: AppBundle\Controller\ChecklistController

ticket:
    type: rest
    resource: AppBundle\Controller\SupportTicketController

testimonial:
    type: rest
    resource: AppBundle\Controller\TestimonialController