login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

login/advanced:
    type: rest
    resource: AppBundle\Controller\RestLoginController


reminder:
    type: rest
    resource: AppBundle\Controller\ReminderController

password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController


profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController


registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController


project:
    type: rest
    resource: AppBundle\Controller\ProjectController


company:
    type: rest
    resource: AppBundle\Controller\CompanyController


reminder:
    type: rest
    resource: AppBundle\Controller\ReminderController


server:
    type: rest
    resource: AppBundle\Controller\ServerController


server_reminder:
    type: rest
    resource: AppBundle\Controller\ServerReminderController


checklist:
    type: rest
    resource: AppBundle\Controller\ChecklistController


ticket:
    type: rest
    resource: AppBundle\Controller\SupportTicketController


testimonial:
    type: rest
    resource: AppBundle\Controller\TestimonialController